plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.creedvi'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(files("assets/Raylib-J.jar"))
}

jar {
    manifest {
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.build.dependsOn jar

sourceSets {
    main {
        java.srcDir('src/main')
    }
    test {
        java.srcDir('src/tests')
        resources.srcDir('assets')
    }
}

publishing {
    publications {
        M3DJ(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "io.github.creedvi"
            url = layout.buildDirectory.dir("repo")
        }
    }
}